//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StepTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int id { get; set; }
        public string initials { get; set; }
        public int age { get; set; }
        public string gender { get; set; }
    
        public virtual UserPreviousResult UserPreviousResult { get; set; }
    }
}
