//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StepTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPreviousResult
    {
        public string initials { get; set; }
        public System.DateTime Date_of_Test { get; set; }
        public int Chosen_Step_Height { get; set; }
        public decimal Max_HR { get; set; }
        public Nullable<decimal> C80__of_Max_HR { get; set; }
        public decimal C50__of_Max_HR { get; set; }
        public decimal HR_stage_1_reading { get; set; }
        public decimal HR_stage_2_reading { get; set; }
        public decimal HR_stage_3_reading { get; set; }
        public decimal HR_stage_4_reading { get; set; }
        public decimal HR_stage_5_reading { get; set; }
        public decimal Aerobic_Capacity { get; set; }
        public string Fitness_Rating { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
